### PR TITLE
Add Glycerine into the "Data Annotation" section

### PR DESCRIPTION
**Pull request by yangli0516**
Add "Glycerine" to the "Data Annotation" section.

**Short pitch**

[Glycerine](https://glycerine.io/) provides a suite of annotation tools and end-to-end workflows for researchers, curators and students to collaborate on projects across repositories. Images can be organized into collections and shared with collaborators. Sets of annotations can combine semantic tags from domain-specific vocabularies with critical analysis in multiple languages. Annotated images can be published as research outputs in immersive and engaging visualizations and archived in sustainable formats.

## Checklist

- [x] I have read and understood the [contribution guidelines](https://github.com/writing-resources/awesome-scientific-writing/blob/main/CONTRIBUTING.md).
- [x] Table of contents has been updated (if a section is added / removed).
- [x] Contents have been sorted alphabetically.

### CODE REVIEW

**Comment by maehr** [comment]
@yangli0516 Out of curiosity, are there any research projects using Glycerine that you could share with us? I haven't heard of it or used it yet.

**Comment by IanMcCrabb** [comment]
Hi @maehr   Glycerine was developed over the last year with funding from https://ardc.edu.au/services/ardc-community-data-lab/  and was launched just last month https://groups.google.com/g/iiif-discuss/c/jkknN6SJK4U.  

It's being used on 3 projects so far: Gandharan Buddhas https://gandhari-texts.sydney.edu.au/collections/gandhari-inscribed-buddhas/,  Upper Indus https://upper-indus.performx.com.au/ and Opening Australias Multilingual Archive https://[omaa-arts.sydney.edu.au](https://omaa-arts.sydney.edu.au/)/.   The initial focus has been on the GLAM sector in Australia, but we host the platform for international researchers as well accessed from https://glycerine.io/.  Best Ian

**Review by maehr — APPROVED** [review]

**Comment by IanMcCrabb** [comment]
Hi @maehr apologies in advance for chasing this, but I presume we are just waiting on a reviewer.  Is there anything else you might need from us?  All the best Ian

**Comment by maehr** [comment]
> Hi @maehr apologies in advance for chasing this, but I presume we are just waiting on a reviewer.  Is there anything else you might need from us?  All the best Ian

Hi Ian

I requested reviews from other collaborators. I hope this will speed up the process.

**Comment by IanMcCrabb** [comment]
Thanks @maehr

**Review by davekelly — APPROVED** [review]

**Pull request merged**
